version: 2.3.{build}

environment:
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

install:
  - ps: Install-Product node 5
  - cd src
  - npm install
  - node_modules\.bin\bower install

build_script:
  - node_modules\.bin\grunt build

test_script:
  - node_modules\.bin\grunt test

after_test:
  - node_modules\.bin\grunt publish
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName ReleaseArtifacts }
  
artifacts: 
  - path: .\*.zip
    name: ReleaseArtifacts

deploy:
  provider: GitHub
  auth_token:
    secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
  artifact: ReleaseArtifacts
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX